### ISSUE TITLE
HTTP Error

### ISSUE THREAD

**Issue by Rajo03** [timotheeMM/gui-youtube-downloader#10]
urllib.error.HTTPError: HTTP Error 410: Gone for every video

**Comment by timotheeMM** [comment]
Hello @Rajo03,
Thank you for reporting this issue.
Could you elaborate on the context in which you encountered this error.
Thanks in advance.

**Comment by timotheeMM** [comment]
Hello @Rajo03 ,
I retested a video download and found no abnormalities.
Here is a video capture of my test and I don’t think the problem comes from the code itself:

[video-capture.webm](https://github.com/timotheeMM/gui-youtube-downloader/assets/143833750/d3bd53cd-b025-4be4-bb29-e8658f85540e)

Maybe you have an older version of pytube.
Here are the solutions of people who have had the same problem as you:

https://stackoverflow.com/questions/68680322/pytube-urllib-error-httperror-http-error-410-gone
